### PR TITLE
feat: Use async await

### PR DESCRIPTION
**Pull request by achingbrain**
This follows on from libp2p/js-libp2p-crypto-secp256k1#9 (not sure why it's a PR from @alanshaw's personal account instead of a branch here 🤷‍♂) but fixes the merge conflicts and updates the deps.

### CODE REVIEW

**Comment by achingbrain** [comment]
@jacobheun @vasco-santos any comments on this or can it be merged?

**Comment by vasco-santos** [comment]
I will have a look now @achingbrain

**Review by vasco-santos — APPROVED** [review]
This LGTM!

Two observations: 

@achingbrain can you add to the commit message the `BREAKING CHANGE`, or @dignifiedquire please add it before squash and merge.

There are several errors coming from `libp2p-crypto`, which should have a code. However, as this PR is for migrating to async await, we should do those changes in a next PR, but maybe we should create an issue for tracking this?

**Comment by achingbrain** [comment]
It's probably easy enough to just add a `BREAKING CHANGE` message when squashing & merging?

**Comment by vasco-santos** [comment]
@achingbrain I agree. Just pointed out to not be forgotten 😄

**Comment by achingbrain** [comment]
@dignifiedquire any comments or can this be merged & released?

**Review by dignifiedquire — APPROVED** [review]

**Comment by dignifiedquire** [comment]
looks good to me

**Comment by achingbrain** [comment]
@dignifiedquire great!  Could you merge & do a release please?  I think only you and @daviddias have publish rights for this module on npm.

**Review by alanshaw — APPROVED** [review]

**Comment by jacobheun** [comment]
0.4.0 is released with breaking change commit note. 🚢

**Pull request merged**
