### PR TITLE
Adds id() method to Secp256k1PrivateKey

### PR DESCRIPTION
**Pull request by AlbertoElias**
Feature parity with ed25519 and rsa

### CODE REVIEW

**Comment by AlbertoElias** [comment]
This is blocking https://github.com/libp2p/js-libp2p-keychain/issues/30

**Comment by AlbertoElias** [comment]
Hey @dignifiedquire could you review please?

**Review by dignifiedquire — COMMENTED** [review]
lgtm

**Comment by AlbertoElias** [comment]
@dignifiedquire great! I don't have write permissions. Could you merge and release? Thank you!

**Review by vasco-santos — APPROVED** [review]
LGTM

**Comment by vasco-santos** [comment]
@dignifiedquire can we get this merged and released?

**Comment by dignifiedquire** [comment]
published, as `0.3.0` (sorry meant to do it as patch, but feature made me think of minor release)

**Pull request merged**
